<?php 
  use Illuminate\Database\Seeder; 
 class PrivateNewsTableSeeder extends Seeder{ public function run(){ 


DB::table('private_news')->insert(['day'     => 1,'type'    => 1,'news_ru'    => 'Социальная сеть Facebook сообщила о массовом взломе. Данные почти 1.5 миллиардов человек попали в открытый доступ.', 'news_en'    => 'Social network Facebook reported a massive hack. The data of nearly 1.5 billion people were made publicly available.','visible'    => 0,'daily_losses' => 0,'solution' => '13', 'just_today' => 0, 'outcomes_good' => '21', 'outcomes_bad' => 'NULL', 'cash_loss' => '200' ]); 

DB::table('private_news')->insert(['day'     => 1,'type'    => 1,'news_ru'    => '"Колличество интернет-угроз в этом году увеличилось на 20%" - сообщает газета Известия.', 'news_en'    => '"The number of Internet threats this year has increased by 20%," the Izvestia newspaper reports.','visible'    => 0,'daily_losses' => 0,'solution' => '3', 'just_today' => 0, 'outcomes_good' => '12', 'outcomes_bad' => 'NULL', 'cash_loss' => '200' ]); 

DB::table('private_news')->insert(['day'     => 1,'type'    => 2,'news_ru'    => 'Вам подкинули флешку в почтовый ящик. Флешка лежала в конверте, внутри конверта небыло больше ничего. Какие-либо опозновательные знаки также отсутствовали.', 'news_en'    => 'You were given a USB flash drive in your mailbox. The flash drive was in the envelope, there was nothing else inside the envelope. There were also no identification marks.','visible'    => 0,'daily_losses' => 0,'solution' => '26', 'just_today' => 0, 'outcomes_good' => '22', 'outcomes_bad' => '8', 'cash_loss' => '220' ]); 

DB::table('private_news')->insert(['day'     => 1,'type'    => 2,'news_ru'    => 'Сообщение на электронную почту от генерального директора', 'description_ru' => 'Привет, слушай ты завтра летишь в  командировку, завтра после работы, перед вылетом, в аэропорту сможешь отправить мне наш финансовый отчет?', 'description_en' => 'Hello, listen, you are on a business trip tomorrow, tomorrow after work, before departure, at the airport can you send me our financial report?', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => '2', 'just_today' => 0, 'outcomes_good' => '1', 'outcomes_bad' => '9', 'cash_loss' => '200' ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 1,'news_ru'    => 'Компания Microsoft официально прекратила поддержку операционной системы Windows 7.', 'news_en'    => 'Microsoft has officially ended support for the Windows 7 operating system.','visible'    => 0,'daily_losses' => 0,'solution' => '7', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '150' ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Ваши пароли в том числе от платежных систем, которые вы хранили в социальной сети "Facebook", помогли опустошить ваши электронные кошельки.', 'news_en'    => 'Your passwords, including those from payment systems that you stored on the Facebook social network, helped empty your e-wallets.','visible'    => 0,'daily_losses' => 0,'solution' => '21', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '430' ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Технология VPN включена и работает в штатном режиме. Весь ваш трафик зашифрован, и проходит через дата-центры Швейцарии.', 'news_en'    => 'VPN technology is enabled and working normally. All your traffic is encrypted and goes through Swiss data centers.','visible'    => '2','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Сообщение на электронную почту от генерального директора', 'description_ru' => 'Кто-то отправил нашим конкурентам наш полный фин отчет, что ты мне сегодня отправил... со всеми подробностями. Пожалуйста, только не говори что ты в аэропорту с вай-фая отправлял отчет', 'description_en' => 'Email message from CEO', 'news_en'    => 'Someone sent our competitors our full financial report that you sent me today ... with all the details. Please do not tell me that you sent a report from Wi-Fi at the airport.','visible'    => '-2','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Вы проверили свой пароль на компрометацию, ваши данные оказались в публичном доступе. ', 'news_en'    => 'You have checked your password for compromise, your data is in the public domain.','visible'    => '13','daily_losses' => 0,'solution' => '1', 'just_today' => 0, 'outcomes_good' => '9', 'outcomes_bad' => 'NULL', 'cash_loss' => '90' ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Из-за вставленной флешки, домашний компьютер был зашифрован не известным вирусом. Все документы которые находились на компьютере зашифрованы.', 'news_en'    => 'Due to the inserted USB flash drive, the home computer was encrypted by an unknown virus. All documents that were on the computer are encrypted.','visible'    => '25','daily_losses' => 0,'solution' => '8', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => '22', 'cash_loss' => '400' ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Вы успешно избавились от неизвестного USB-накопителя (флешки) которую вам кто-то подбросил.', 'news_en'    => 'You have successfully got rid of an unknown USB drive (flash drive) that someone planted for you.','visible'    => '26','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Антивирус успешно установлен и работает в штатном режиме. Это Вам обеспечит: <br><br>- Блокирование вредоносного ПО и других угроз<br>- Защита от сбора данных<br>- Обнаружение шпионского ПО на Android и IOS устройствах<br>- Защита онлайн-платежей шифрованием<br>- Защита доступа к микрофону<br>- Безопасное соединение для шифрования ценных данных', 'news_en'    => 'The anti-virus has been successfully installed and is working normally. This will provide you with: <br> <br> - Blocking malware and other threats <br> - Protection against data collection <br> - Detecting spyware on Android and IOS devices <br> - Protecting online payments with encryption <br> - Microphone Access Protection <br> - Secure connection to encrypt valuable data','visible'    => '3','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Обновление приложений (операционной системы) прошло успешно.', 'news_en'    => 'The application (operating system) update was successful.','visible'    => '7','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 2,'type'    => 2,'news_ru'    => 'Сообщение от неизвестного контакта +7 (123) 456 79-12', 'description_ru' => 'Привет! Это Жанна - сестра (доказательство: ты мне случайно выбил зуб в 5 лет). Прикинь, меня в метро вытащили телефон. Получили доступ ко всему: фото, видео, контакты, банковское приложение. Уже многим звонят и говорят что со мной что-то случилось, просят деньги. Если что смело ложи трубку.<br><br>Но это даже не самое главное, смодешь мне скинуть все фотки, совместыне, нет доступа ни к чему!', 'description_en' => 'Message from an unknown contact +7 (123) 456 79-12', 'news_en'    => 'Hey! This is Jeanne - a sister (proof: you accidentally knocked out my tooth at the age of 5). Count me, my phone was pulled out in the subway. Got access to everything: photos, videos, contacts, banking application. Already many people are calling and saying that something has happened to me, asking for money. If something boldly lodge a phone. <br> <br> But this is not even the most important thing, you can throw off all the photos, together, there is no access to anything!','visible'    => 0,'daily_losses' => 0,'solution' => '12', 'just_today' => 0, 'outcomes_good' => '10', 'outcomes_bad' => 'NULL', 'cash_loss' => '100' ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 1,'news_ru'    => 'Крупный Российский банк добавил функцию верификации аккаунтов через биометрические данные со сканера отпетка пальцев телефона, а также полноценную двухфакторную аутентификацию.', 'news_en'    => 'A large Russian bank has added the function of verifying accounts through biometric data from a fingerprint scanner, as well as full two-factor authentication.','visible'    => 0,'daily_losses' => 0,'solution' => '9', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '120' ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'СМС от контакта "Супруг"', 'description_ru' => 'Дорогой, приходил мастер, установил вай-фай, как будешь дома можешь подключаться он без пароля.', 'description_en' => 'SMS from the contact "Spouse"', 'news_en'    => 'Dear, the master came, installed the wi-fi, as you are at home you can connect it without a password.','visible'    => 0,'daily_losses' => 0,'solution' => '18', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => '24', 'cash_loss' => '50' ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Менеджер паролей был успешно установлен. Выбранный вами менеджер паролей удовлетворяет всем требованиям надежности:<br><br>- Доступ к хранилищу с помощью мастер-пароля или по отпечатку пальца (с мобильных устройств)<br>- Уведомление о недостаточно надежных паролях<br>- Предупреждение о дублирующихся паролях<br>- Создание надежных паролей для новых учетных записей<br>- Автоочистка буфера (кнопки копировать) для дополнительной защиты данных<br><br>Также менеджер паролей включает: <br><br>- Автоматическая авторизация в ваших учетных записях<br>- Надежные уникальные пароли для новых учетных записей<br>- Автоматическое заполнение адресов для экономии времени*<br>- Безопасный ввод данных банковских карт<br>', 'news_en'    => 'The password manager has been successfully installed. The password manager you have chosen meets all the security requirements: <br> <br> - Access to the vault using a master password or fingerprint (from mobile devices) <br> - Notification about insufficiently strong passwords <br> - Alerting about duplicate passwords <br> - Create strong passwords for new accounts <br> - Autoclean buffer (copy buttons) for additional data protection <br> <br> Password manager also includes: <br> <br> - Automatic authorization in your accounts < br> - Strong unique passwords for new accounts <br> - Automatically fill in addresses to save time * <br> - Safely enter bank card details <br>','visible'    => '21','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Технология VPN включена и раюотает в штатном режиме. Весь ваш трафик зашифрован, и проходит через дата-центры Швейцарии.', 'news_en'    => 'VPN technology is on and working normally. All your traffic is encrypted and goes through Swiss data centers.','visible'    => '2','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Вы проверили свой пароль на компрометацию, ваши данные оказались в публичном доступе. ', 'news_en'    => 'You have checked your password for compromise, your data is in the public domain.','visible'    => '13','daily_losses' => 0,'solution' => '1', 'just_today' => 0, 'outcomes_good' => '9', 'outcomes_bad' => 'NULL', 'cash_loss' => '90' ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Из-за вставленной флешки, домашний компьютер был зашифрован не известным вирусом. Все документы которые находились на компьютере зашифрованы.', 'news_en'    => 'Due to the inserted USB flash drive, the home computer was encrypted by an unknown virus. All documents that were on the computer are encrypted.','visible'    => '25','daily_losses' => 0,'solution' => '8', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => '22', 'cash_loss' => '400' ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Вы успешно избавились от неизвестного USB-накопителя (флешки) которую вам кто-то подбросил.', 'news_en'    => 'You have successfully got rid of an unknown USB drive (flash drive) that someone planted for you.','visible'    => '26','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Антивирус успешно установлен и работает в штатном режиме. Это Вам обеспечит: <br><br>- Блокирование вредоносного ПО и других угроз<br>- Защита от сбора данных<br>- Обнаружение шпионского ПО на Android и IOS устройствах<br>- Защита онлайн-платежей шифрованием<br>- Защита доступа к микрофону<br>- Безопасное соединение для шифрования ценных данных', 'news_en'    => 'The anti-virus has been successfully installed and is working normally. This will provide you with: <br> <br> - Blocking malware and other threats <br> - Protection against data collection <br> - Detecting spyware on Android and IOS devices <br> - Protecting online payments with encryption <br> - Microphone Access Protection <br> - Secure connection to encrypt valuable data','visible'    => '3','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Обновление приложений (операционной системы) прошло успешно.', 'news_en'    => 'The application (operating system) update was successful.','visible'    => '7','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Пароль на ваш телефон был успешно установлен, теперь только вы сможете воспользоваться устройством.', 'news_en'    => 'The password has been successfully set on your phone, now only you can use the device.','visible'    => '12','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Вы вызвали службу безопасности во время работы, ничего подозрительного на вашем компьюетере она не обнаружила.', 'news_en'    => 'Вы вызвали службу безопасности во время работы, ничего подозрительного на вашем компьюетере она не обнаружила.','visible'    => '22','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Пароли социальных сетей были успешно изменены.', 'news_en'    => '','visible'    => '1','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Полное сканирование устройства антивирусом завершено, проблем не обнаружено!', 'news_en'    => '','visible'    => '8','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Двухфакторная аутентификация для банковсокго приоржения была включена успешно. Теперь после любой операции по счету карты (снятие денег/внесение денег/перевод денег на другой счет) вам будет приходить оповещение.			', 'news_en'    => '','visible'    => '9','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 3,'type'    => 2,'news_ru'    => 'Операционная система обновлена. Обновление включает:<br><br>- Исправления неполадок системы безопасности<br>- Новый текстовый редактор<br>- Обновление веб-браузера<br>- Обнавление облочной системы хранения документов<br>- Повышение производительности<br><br>При обновлении была повреждена папка "Рабочие документы".', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => '10', 'just_today' => 0, 'outcomes_good' => '24', 'outcomes_bad' => 'NULL', 'cash_loss' => '130' ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 1,'news_ru'    => 'Новостей нет', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => 'NULL', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '0' ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Сообщение на электронную почту от генерального директора', 'description_ru' => 'Привет, это опять я. Слушай, нам срочно нужно отредактировать одну модель. Можешь скачать какой-нибудь редактор сделать это? Правда у нас денег на лицензию нет, так что ты там поаккуратнее..', 'description_en' => '', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => '14', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '270' ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Сообщение на Вашего банка', 'description_ru' => 'Добрый день! Уведомляем Вас об участившихся случаях мошенничества. Все сообщения от банка, рассылаются только с номера 900.<br><br>Также обращаем ваше внимание, что банк никогда не устраивает выплаты средств клиентам "просто-так". В случае, если пришло какое-либо сообщение с опечатка, или с неофициального номера, или же со странным содержимым - всегда звонить в службу поддержки (или службу безопасности) банка. Звонок бесплатный. Номер вы можете найти на обратной стороне свой дебетовой или кредитной карты.', 'description_en' => '', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Менеджер паролей был успешно установлен. Выбранный вами менеджер паролей удовлетворяет всем требованиям надежности:<br><br>- Доступ к хранилищу с помощью мастер-пароля или по отпечатку пальца (с мобильных устройств)<br>- Уведомление о недостаточно надежных паролях<br>- Предупреждение о дублирующихся паролях<br>- Создание надежных паролей для новых учетных записей<br>- Автоочистка буфера (кнопки копировать) для дополнительной защиты данных<br><br>Также менеджер паролей включает: <br><br>- Автоматическая авторизация в ваших учетных записях<br>- Надежные уникальные пароли для новых учетных записей<br>- Автоматическое заполнение адресов для экономии времени*<br>- Безопасный ввод данных банковских карт<br>', 'news_en'    => '','visible'    => '21','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Технология VPN включена и раюотает в штатном режиме. Весь ваш трафик зашифрован, и проходит через дата-центры Швейцарии.', 'news_en'    => '','visible'    => '2','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Вы проверили свой пароль на компрометацию, ваши данные оказались в публичном доступе. ', 'news_en'    => '','visible'    => '13','daily_losses' => 0,'solution' => '1', 'just_today' => 0, 'outcomes_good' => '9', 'outcomes_bad' => 'NULL', 'cash_loss' => '90' ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Из-за вставленной флешки, домашний компьютер был зашифрован не известным вирусом. Все документы которые находились на компьютере зашифрованы.', 'news_en'    => '','visible'    => '25','daily_losses' => 0,'solution' => '8', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => '22', 'cash_loss' => '400' ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Вы успешно избавились от неизвестного USB-накопителя (флешки) которую вам кто-то подбросил.', 'news_en'    => '','visible'    => '26','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Антивирус успешно установлен и работает в штатном режиме. Это Вам обеспечит: <br><br>- Блокирование вредоносного ПО и других угроз<br>- Защита от сбора данных<br>- Обнаружение шпионского ПО на Android и IOS устройствах<br>- Защита онлайн-платежей шифрованием<br>- Защита доступа к микрофону<br>- Безопасное соединение для шифрования ценных данных', 'news_en'    => '','visible'    => '3','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Обновление приложений (операционной системы) прошло успешно.', 'news_en'    => '','visible'    => '7','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Пароль на ваш телефон был успешно установлен, теперь только вы сможете воспользоваться устройством.', 'news_en'    => '','visible'    => '12','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Вы вызвали службу безопасности во время работы, ничего подозрительного на вашем компьюетере она не обнаружила.', 'news_en'    => '','visible'    => '22','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Пароли социальных сетей были успешно изменены.', 'news_en'    => '','visible'    => '1','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Полное сканирование устройства антивирусом завершено, проблем не обнаружено!', 'news_en'    => '','visible'    => '8','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Двухфакторная аутентификация для банковсокго приоржения была включена успешно. Теперь после любой операции по счету карты (снятие денег/внесение денег/перевод денег на другой счет) вам будет приходить оповещение.			', 'news_en'    => '','visible'    => '9','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Паппка "Рабочии документы" - была успешно восстановлена из резервной копии.', 'news_en'    => '','visible'    => '10','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Ваш друг в социальной сети: <br><br>- Друзья, всем салют! Сегодня ехал в автобусе и у меня просто так снялись деньги с пластиковых карт Visa/Mastercard, кто-то подошел со считывающим устройством и снял 3000 рублей с каждой. Будьте аккуартны!', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => '24', 'just_today' => 0, 'outcomes_good' => '8', 'outcomes_bad' => 'NULL', 'cash_loss' => '120' ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Ваш телефон перестал работать. Он по какой-то причине не принимает звонки и СМС сообщения. ', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => '19', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '150' ]); 

DB::table('private_news')->insert(['day'     => 4,'type'    => 2,'news_ru'    => 'Антивирус на рабочем компьютере выявил подозрительную активность.', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => '22', 'just_today' => 0, 'outcomes_good' => '', 'outcomes_bad' => '', 'cash_loss' => '0' ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 1,'news_ru'    => 'Компания из Купертино - Apple, опубликовало отчет о продажах приложений среди пользователей. По статистике до 54% приложений и других покупок делаются детьми с устройств их родителей.', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => '6', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '400' ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Установленное пиратское ПО заблокировало ваш компьютер.', 'news_en'    => '','visible'    => '15','daily_losses' => 0,'solution' => '8', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '130' ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Ваше устройство было успешно починено.', 'news_en'    => '','visible'    => '19','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'В процессе ремонта, было выявлено,что повреждена матрица, и она также требует замены, пожалуйста заплатите дополнительные 150 долларов.', 'news_en'    => '','visible'    => '20','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Сообщение на электронную почту от генерального директора', 'description_ru' => 'Сегодня была гос. проверка, у тебя на рабочем месте нашли пиратское ПО. Тперь благодаря тебе мы выплатим штраф в 5000 долларов. И еще, я лишаю тебя премии.', 'description_en' => '', 'news_en'    => '','visible'    => '15','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Вы вызвали службу безопасности для реакции на инцидент, что оказалось важным для защиты вашей компании..', 'news_en'    => '','visible'    => '22','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Менеджер паролей был успешно установлен. Выбранный вами менеджер паролей удовлетворяет всем требованиям надежности:<br><br>- Доступ к хранилищу с помощью мастер-пароля или по отпечатку пальца (с мобильных устройств)<br>- Уведомление о недостаточно надежных паролях<br>- Предупреждение о дублирующихся паролях<br>- Создание надежных паролей для новых учетных записей<br>- Автоочистка буфера (кнопки копировать) для дополнительной защиты данных<br><br>Также менеджер паролей включает: <br><br>- Автоматическая авторизация в ваших учетных записях<br>- Надежные уникальные пароли для новых учетных записей<br>- Автоматическое заполнение адресов для экономии времени*<br>- Безопасный ввод данных банковских карт<br>', 'news_en'    => '','visible'    => '21','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Технология VPN включена и раюотает в штатном режиме. Весь ваш трафик зашифрован, и проходит через дата-центры Швейцарии.', 'news_en'    => '','visible'    => '2','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Вы проверили свой пароль на компрометацию, ваши данные оказались в публичном доступе. ', 'news_en'    => '','visible'    => '13','daily_losses' => 0,'solution' => '1', 'just_today' => 0, 'outcomes_good' => '9', 'outcomes_bad' => 'NULL', 'cash_loss' => '90' ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Из-за вставленной флешки, домашний компьютер был зашифрован не известным вирусом. Все документы которые находились на компьютере зашифрованы.', 'news_en'    => '','visible'    => '25','daily_losses' => 0,'solution' => '8', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => '22', 'cash_loss' => '400' ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Вы успешно избавились от неизвестного USB-накопителя (флешки) которую вам кто-то подбросил.', 'news_en'    => '','visible'    => '26','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Антивирус успешно установлен и работает в штатном режиме. Это Вам обеспечит: <br><br>- Блокирование вредоносного ПО и других угроз<br>- Защита от сбора данных<br>- Обнаружение шпионского ПО на Android и IOS устройствах<br>- Защита онлайн-платежей шифрованием<br>- Защита доступа к микрофону<br>- Безопасное соединение для шифрования ценных данных', 'news_en'    => '','visible'    => '3','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Обновление приложений (операционной системы) прошло успешно.', 'news_en'    => '','visible'    => '7','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Пароль на ваш телефон был успешно установлен, теперь только вы сможете воспользоваться устройством.', 'news_en'    => '','visible'    => '12','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Вы вызвали службу безопасности во время работы, ничего подозрительного на вашем компьюетере она не обнаружила.', 'news_en'    => '','visible'    => '22','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Пароли социальных сетей были успешно изменены.', 'news_en'    => '','visible'    => '1','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Полное сканирование устройства антивирусом завершено, проблем не обнаружено!', 'news_en'    => '','visible'    => '8','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Двухфакторная аутентификация для банковсокго приоржения была включена успешно. Теперь после любой операции по счету карты (снятие денег/внесение денег/перевод денег на другой счет) вам будет приходить оповещение.			', 'news_en'    => '','visible'    => '9','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Паппка "Рабочии документы" - была успешно восстановлена из резервной копии.', 'news_en'    => '','visible'    => '10','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Вы успешно установили пароль на ваш Wi-Fi и включили шифрование данных.', 'news_en'    => '','visible'    => '18','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Вы купили антискимминговый чехол, теперь ваши пластиковые карты под защитой от несанкционированного тач-снятия денег.', 'news_en'    => '','visible'    => '24','daily_losses' => 0,'solution' => NULL, 'just_today' => 0, 'outcomes_good' => NULL, 'outcomes_bad' => NULL, 'cash_loss' => NULL ]); 

DB::table('private_news')->insert(['day'     => 5,'type'    => 2,'news_ru'    => 'Ваш друг в социальной сети опубликовал пост об опасности веб-камеры. <br><br><br>Сегодня листал ленту в социальной сети, вижу пост мистера Цукерберга. Вроде бы обычная фотка, все ок. Но, неееет, у него заклеяна веб-камера. <br><br>Как думаете почему это вообще важно?  ', 'news_en'    => '','visible'    => 0,'daily_losses' => 0,'solution' => '23', 'just_today' => 0, 'outcomes_good' => 'NULL', 'outcomes_bad' => 'NULL', 'cash_loss' => '340' ]); 

}}